import fs from 'node:fs';

const out = `
  {
    id: 'worker69_f_1',
    kind: 'npc',
    source: 'first_party_art',
    sourcePath: 'arts/69worker_f_1.png',
    sha256: '',
    width: 0,
    height: 0,
    anchorFeet: { x: 32, y: 61 },
    portraitCrop: { x: 16, y: 4, w: 32, h: 40 },
    author: 'first_party',
    sourceNote: 'manual pixel art',
    consent: 'project_owned',
    intendedMappings: [{
      type: 'npc_family',
      visualId: NPC_VISUAL_WORKER69,
      occupation: 'WORKER69',
      sex: 'female',
      variant: '1',
    }],
  },
  {
    id: 'worker69_f_2',
    kind: 'npc',
    source: 'first_party_art',
    sourcePath: 'arts/69worker_f_2.png',
    sha256: '',
    width: 0,
    height: 0,
    anchorFeet: { x: 32, y: 61 },
    portraitCrop: { x: 16, y: 4, w: 32, h: 40 },
    author: 'first_party',
    sourceNote: 'manual pixel art',
    consent: 'project_owned',
    intendedMappings: [{
      type: 'npc_family',
      visualId: NPC_VISUAL_WORKER69,
      occupation: 'WORKER69',
      sex: 'female',
      variant: '2',
    }],
  },
  {
    id: 'worker69_f_3',
    kind: 'npc',
    source: 'first_party_art',
    sourcePath: 'arts/69worker_f_3.png',
    sha256: '',
    width: 0,
    height: 0,
    anchorFeet: { x: 32, y: 61 },
    portraitCrop: { x: 16, y: 4, w: 32, h: 40 },
    author: 'first_party',
    sourceNote: 'manual pixel art',
    consent: 'project_owned',
    intendedMappings: [{
      type: 'npc_family',
      visualId: NPC_VISUAL_WORKER69,
      occupation: 'WORKER69',
      sex: 'female',
      variant: '3',
    }],
  },
  {
    id: 'worker69_f_4',
    kind: 'npc',
    source: 'first_party_art',
    sourcePath: 'arts/69worker_f_4.png',
    sha256: '',
    width: 0,
    height: 0,
    anchorFeet: { x: 32, y: 61 },
    portraitCrop: { x: 16, y: 4, w: 32, h: 40 },
    author: 'first_party',
    sourceNote: 'manual pixel art',
    consent: 'project_owned',
    intendedMappings: [{
      type: 'npc_family',
      visualId: NPC_VISUAL_WORKER69,
      occupation: 'WORKER69',
      sex: 'female',
      variant: '4',
    }],
  },
  {
    id: 'worker69_m_1',
    kind: 'npc',
    source: 'first_party_art',
    sourcePath: 'arts/69worker_m_1.png',
    sha256: '',
    width: 0,
    height: 0,
    anchorFeet: { x: 32, y: 61 },
    portraitCrop: { x: 16, y: 4, w: 32, h: 40 },
    author: 'first_party',
    sourceNote: 'manual pixel art',
    consent: 'project_owned',
    intendedMappings: [{
      type: 'npc_family',
      visualId: NPC_VISUAL_WORKER69,
      occupation: 'WORKER69',
      sex: 'male',
      variant: '1',
    }],
  },`;

let oldContent = fs.readFileSync('src/data/art_sprite_manifest.ts', 'utf8');

// Replace worker69_1 and worker69_2 blocks
oldContent = oldContent.replace(/  \{\n    id: 'worker69_1',[\s\S]*?      variant: '2',\n    \}\],\n  \},/, out.trim());

// We also need to add new liquidators
const newLiquidators = `
  {
    id: 'liquidator_m_4',
    kind: 'npc',
    source: 'first_party_art',
    sourcePath: 'arts/liquidator_m_4.png',
    sha256: '',
    width: 0,
    height: 0,
    anchorFeet: { x: 32, y: 61 },
    portraitCrop: { x: 16, y: 4, w: 32, h: 40 },
    author: 'first_party',
    sourceNote: 'manual pixel art',
    consent: 'project_owned',
    intendedMappings: [{
      type: 'npc_family',
      visualId: NPC_VISUAL_LIQUIDATOR_MALE,
      faction: 'LIQUIDATOR',
      sex: 'male',
      variant: '4',
    }],
  },
  {
    id: 'liquidator_m_5',
    kind: 'npc',
    source: 'first_party_art',
    sourcePath: 'arts/liquidator_m_5.png',
    sha256: '',
    width: 0,
    height: 0,
    anchorFeet: { x: 32, y: 61 },
    portraitCrop: { x: 16, y: 4, w: 32, h: 40 },
    author: 'first_party',
    sourceNote: 'manual pixel art',
    consent: 'project_owned',
    intendedMappings: [{
      type: 'npc_family',
      visualId: NPC_VISUAL_LIQUIDATOR_MALE,
      faction: 'LIQUIDATOR',
      sex: 'male',
      variant: '5',
    }],
  },
  {
    id: 'liquidator_m_6',
    kind: 'npc',
    source: 'first_party_art',
    sourcePath: 'arts/liquidator_m_6.png',
    sha256: '',
    width: 0,
    height: 0,
    anchorFeet: { x: 32, y: 61 },
    portraitCrop: { x: 16, y: 4, w: 32, h: 40 },
    author: 'first_party',
    sourceNote: 'manual pixel art',
    consent: 'project_owned',
    intendedMappings: [{
      type: 'npc_family',
      visualId: NPC_VISUAL_LIQUIDATOR_MALE,
      faction: 'LIQUIDATOR',
      sex: 'male',
      variant: '6',
    }],
  },`;

oldContent = oldContent.replace(/  \{\n    id: 'liquidator_f_1',/, newLiquidators.trim() + '\n  {\n    id: \'liquidator_f_1\',');

const newScientists = `
  {
    id: 'scientist_m_3',
    kind: 'npc',
    source: 'first_party_art',
    sourcePath: 'arts/scientist_m_3.png',
    sha256: '',
    width: 0,
    height: 0,
    anchorFeet: { x: 32, y: 61 },
    portraitCrop: { x: 16, y: 4, w: 32, h: 40 },
    author: 'first_party',
    sourceNote: 'manual pixel art',
    consent: 'project_owned',
    intendedMappings: [{
      type: 'npc_family',
      visualId: NPC_VISUAL_SCIENTIST_MALE,
      faction: 'SCIENTIST',
      sex: 'male',
      variant: '3',
    }],
  },
  {
    id: 'scientist_m_4',
    kind: 'npc',
    source: 'first_party_art',
    sourcePath: 'arts/scientist_m_4.png',
    sha256: '',
    width: 0,
    height: 0,
    anchorFeet: { x: 32, y: 61 },
    portraitCrop: { x: 16, y: 4, w: 32, h: 40 },
    author: 'first_party',
    sourceNote: 'manual pixel art',
    consent: 'project_owned',
    intendedMappings: [{
      type: 'npc_family',
      visualId: NPC_VISUAL_SCIENTIST_MALE,
      faction: 'SCIENTIST',
      sex: 'male',
      variant: '4',
    }],
  },`;

oldContent = oldContent.replace(/  \{\n    id: 'scientist_f_1',/, newScientists.trim() + '\n  {\n    id: \'scientist_f_1\',');

const newScientistsF = `
  {
    id: 'scientist_f_2',
    kind: 'npc',
    source: 'first_party_art',
    sourcePath: 'arts/scientist_f_2.png',
    sha256: '',
    width: 0,
    height: 0,
    anchorFeet: { x: 32, y: 61 },
    portraitCrop: { x: 16, y: 4, w: 32, h: 40 },
    author: 'first_party',
    sourceNote: 'manual pixel art',
    consent: 'project_owned',
    intendedMappings: [{
      type: 'npc_family',
      visualId: NPC_VISUAL_SCIENTIST_FEMALE,
      faction: 'SCIENTIST',
      sex: 'female',
      variant: '2',
    }],
  },`;

oldContent = oldContent.replace(/  \{\n    id: 'citizen_m_1',/, newScientistsF.trim() + '\n  {\n    id: \'citizen_m_1\',');

fs.writeFileSync('src/data/art_sprite_manifest.ts', oldContent);
